### ISSUE TITLE
Network: (Partial) Correlation; Threshold Method

### ISSUE THREAD

**Issue by omairess** [jasp-stats/jaspNetwork#41]
Bootnet repeatedly crashes (arg length zero) when selecting any threshold method (fdr, significant, Bonferroni, etc.) in the analysis options.

Tried different datasets, different complexities and sample sizes from large (>5000 cases) to small (<120), nothing works.

PS: would also be nice to include directed graphs, and networks allowing panel and time series :)

**Comment by vandenman** [comment]
Thanks for the report, could you please create an issue at [github.com/jasp-stats/jasp-issue](https://github.com/jasp-stats/jasp-issues/issues/) (or click [here](https://github.com/jasp-stats/jasp-issues/issues/new?assignees=&labels=&template=bug-report.yml&title=%5BBug%5D%3A+)).

We bundle issues in one repository so that it is easier for us to keep the overview.

Thanks in advance!

**Comment by vandenman** [comment]
This should be fixed by #49, but feel free to reopen if this is not the case.
